baseURL = "https://defend-project.github.io/"
languageCode = "en-US"
defaultContentLanguage = "en"
title = "DEFEND"
theme = "learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/defend-project/defend-project.github.io/edit/main/content/"
  description = "Documentation of Dnaya"
  author = "F. Verri and M. Machado"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = true
  disableMermaid = false
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  titleSeparator = "-"

[outputs]
home = [ "HTML", "RSS", "JSON"]
